apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configwatchers.k8spatterns.com
spec:
  scope: Namespaced
  group: k8spatterns.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                configMap:
                  type: string
                  description: "Name of the ConfigMap to monitor for changes"
                podSelector:
                  type: object
                  description: "Label selector for identifying pods to restart"
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
              required:
                - configMap
                - podSelector
      additionalPrinterColumns:
        - name: ConfigMap
          type: string
          jsonPath: .spec.configMap
  names:
    kind: ConfigWatcher
    singular: configwatcher
    plural: configwatchers
    shortNames:
      - cw
