# SecretProviderClass - Vault에서 Secret 가져오기 정의
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
  namespace: csi-test
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "csi-test"
    objects: |
      - objectName: "db-username"
        secretPath: "secret/data/database"
        secretKey: "username"
      - objectName: "db-password"
        secretPath: "secret/data/database"
        secretKey: "password"
      - objectName: "connection-string"
        secretPath: "secret/data/database"
        secretKey: "connection_string"
  # K8s Secret으로도 동기화 (선택사항)
  secretObjects:
    - secretName: database-creds-synced
      type: Opaque
      data:
        - objectName: db-username
          key: username
        - objectName: db-password
          key: password
