apiVersion: v1
kind: ConfigMap
metadata:
  name: random-generator-config-immutable
  labels:
    pattern: ConfigurationResource
    type: immutable
data:
  PATTERN: "Configuration Resource - Immutable"
  VERSION: "1.0"
  application.properties: |
    # Random Generator config (Immutable)
    log.file=/tmp/generator-immutable.log
    version=1.0
immutable: true
