apiVersion: v1
kind: ConfigMap
metadata:
  name: random-generator-config-mutable
  labels:
    pattern: ConfigurationResource
    type: mutable
data:
  PATTERN: "Configuration Resource - Mutable"
  VERSION: "1.0"
  application.properties: |
    # Random Generator config (Mutable)
    log.file=/tmp/generator.log
    version=1.0
