# 평문 Secret (암호화 전)
# 이 파일은 Git에 커밋하면 안 됩니다!
apiVersion: v1
kind: Secret
metadata:
    name: sops-test-secret
    namespace: sops-test
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:b3H7go4=,iv:1FR2V8PoUIVDoC1rBeuqNVUeGfHjaoSwkvQAq3kA2G0=,tag:gQEoikIYsZJzp7M6XEYq9Q==,type:str]
    password: ENC[AES256_GCM,data:8E2nyH+W7GL6mno/r8lPQOvLuILgZid6,iv:oauvFlRAMsB+HSCvCzNS2NgHlcKygOJsFPMXakApr/Q=,tag:hITk6qrLKrYjYpAY1ugc8Q==,type:str]
    api-key: ENC[AES256_GCM,data:nCpqdKrCRn403n8/Wy95g5BQUQ==,iv:7Ykt03FjEW/oDUccueKiTYbY3gz5tLHPac/o+0PWa8c=,tag:G8rowTuh7GHmCUDhZhmkWw==,type:str]
sops:
    age:
        - recipient: age1zs4kgau8386ejx8mrt2kdh0wula39l3mscz9nl6c00xenc835v0qgspnma
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTHFqWmpIUkpBd1Z4MEQ2
            WnZWNkFaMm43VU5mb0VLMGdSbkl6dEcrUHhzCkZBdURwcG9QVTF5bUtYVXkxMGh1
            K1BaL2puSlNibXhBNXM0eHFFMkZWdUEKLS0tIHhKcEZKcndIazVINE5yY2xaakdM
            R1Y0eEIwY3VQNXJ2dVVmQzZpRHBRUlEKztFK/Fy1bKfsHjWckK/IvwXe1hnOHYGG
            ESJg7TKMIeR5VdUsPnTRa+RHtW0RPXGV1i69Aijhkz/FumpWIDRlUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T10:34:35Z"
    mac: ENC[AES256_GCM,data:BV6q6bI4miHxxx+7XhJo0iQ/KqbJ0c0mxpD6c3BD4wFEm4xYqvDldcVPwh+5EyYvHdUMRyj/11bvUoGCrzrL0xFWDgX1g98M6Bt2N8ACCCJff+ud3G965cWz5DXcDgzPp2fkZ+Jmu8IHEaqeYKrYUIL6IkhErbbS0QsE+LfaCYg=,iv:zCDl+0d3Z1VKZj1WiQsTSupVbS0ktAeMF/EDzb9Mzw4=,tag:KKP+efTmadhMaNUkHXPs2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
